---
title: "Algumas reflexões sobre concursos acadêmicos e pesquisa"
weight: 1
subtitle: ""
excerpt: ""
date: 2023-01-28
lastmod: 2023-01-28
draft: false
tags: 
  - Academic life
  - Academia
---


Dias atrás me deparei com uma postagem de um colega de academia na rede do passarinho azul. Ele relatava sua insatisfação com o sistema de seleção de professores para carreira acadêmica através do atual formato dos concursos públicos, que basicamente é uma processo que consiste em três etapas: prova escrita (eliminatória), prova didática (eliminatória) e prova de títulos (classificatória). De maneira muito simplificada estas três etapas definem o objetivo profissional final de muitos doutores no Brasil. 
Voltando a postagem, a principal queixa, era referente ao peso desproporcional dado a prova escrita em detrimento de conquistas acadêmicas (vou discutir um pouco mais esse termo adiante). Uma vez eliminada/eliminado da prova escrita, fim da linha. A conclusão então era que, uma vida dedicada a pesquisa e, mesmo recheada de conquistas acadêmicas, não garantiria uma vaga como professor/professora no Brasil. 

Fiquei pensando sobre duas coisas, e esse texto é uma tentativa de organizar os pensamentos referentes as críticas em relação ao sistema de concursos para professores universitários no Brasil.

Um texto que começa com a justificativa dos argumentos nele contido já é fadado a contradição em certa extensão, mas tudo bem, assumo esse fato. Portanto, antes de apresentar os dois pontos, tenho que deixar claro que concordo com o argumento de que as provas escritas, da maneira como são feitas nos concursos públicos no Brasil, não avaliam necessáriamente o mérito científico, e, portanto, não estão perto de serem a melhor forma de seleção de um professor universitário.

Mas voltando ao ponto deste texto, a questão que se coloca é: aumentar a valorização de conquistas acadêmicas (ou mérito científico) no processo seletivo de concursos públicos de professores/professoras universitário torna esse processo mais justo e isonômico? Para abordar essa questão quero discutir dois pontos: 

1. Assumindo que podemos quantificar de maneira objetiva e isonômica o que estamos chamando de conquistas acadêmicas/mérito acadêmico, minha primeira ressalva, que está mais para um questionamento, é, **as conquistas acadêmicas representam de maneira inequívoca a qualidade profissional de um professor universitário?**. Em outras palavras, estas conquistas estão livres dos viéses geográficos/sociais inerentes ao sistema acadêmico brasileiro? Ou no vocabulário do pesquisador, qual a probabilidade de atribuirmos corretamente as conquistas acadêmicas ao mérito acadêmico, quando controlamos por outros fatores (o famoso problema da autocorrelação em ecologia).

2. O argumento relativo a **idiossincrasia do sistema de seleção em concursos públicos no Brasil**. É verdade que fora do Brasil não há um sistema de seleção que envolva uma fase eliminatória com prova escrita. Porém, a ausência deste tipo de seleção também não garante a isonomia do processo, na realidade este sistema pode ter o efeito contrário, favorecendo a manutenção de "linhagens" de acadêmicos vindos de universidades ou supervisores prestigiosos. 

Vou tentar desenvolver estes dois pontos em mais detalhes a seguir.

## As conquistas acadêmicas representam de maneira inequívoca a qualidade profissional de professor universitário?

Imagino que é de concordância geral que o Brasil é um país atolado de desigualdades até a cabeça, seria isso diferente em relação ao meio acadêmico? Creio que não. O sistema universitário apresentou uma grande expansão com o [REUNI](https://reuni.mec.gov.br/). Inúmeras universidades surgiram para além do eixo sul-sudeste e capitais do Brasil. Apesar de todos os benefícios, principalmente por tornar a universidade um local possível de ser alcançado por uma grande parte da população antes excluída, o custo foi a criação de unidades e universidades que não apresentavam a mesma infra-estrutura e recursos que as já estabelecidas universidades do eixo sul-sudeste e capitais. Consequentemente, estudantes formados nos novos campus do interior, muitas vezes apenas em cursos de licenciatura, com foco distante da pesquisa academica, saem com bagagem teórica e prática muito inferior a estudantes formados em grandes universidades (USP, UnB, UFRGS, UFRJ etc.). Consequentemente, não é difícil imaginar que a conquista de uma posição acadêmica permanente de professor começa em linhas de largada diferentes dependendo do local de formação. 

Em um [ótimo artigo](https://files.cercomp.ufg.br/weby/up/711/o/Diniz-Filho_etal2016_Journal_of_Infometrics.pdf) do professor José Alexandre Diniz-Filho e colegas, eles mostram que o fator que mais afetou o desempenho acadêmico de professores na Universidade Federal de Goiás (medido através de uma métrica que pondera a quantidade de artigos e onde estes foram publicados) foi a produção destes quando ainda graduandos. Dada esta informação vamos pensar na seguinte situação. Um laboratório de pesquisa no interior do Brasil, longe dos grandes polos de pesquisa, com um curso de licenciatura onde o estudante precisa apresentar um trabalho de conclusão voltado para a área de ensino. Nas universidades tradicionais do Brasil, invariávelmente o estudante terá a opção de cursar um bacharelado, que apresenta uma grade curricular voltada para pesquisa, além da vivência em laboratórios que apresentam um orientador e provavelmente mais uns tantos mestrandos, doutorandos, e não raramente alguns pós doutorandos. Todos estes discutindo durante muitas horas sobre publicação de artigos acadêmicos. A lógica é mais ou menos a mesma do músico que é filho e netos de músicos. Frente a essa situação, podemos nos perguntar: Quais dos dois estudantes terá uma maior probabilidade de obter conquistas acadêmicas, se essas forem medidas como publicação de artigos científicos? Acredito que não é uma resposta difícil. Desta maneira, é difícil dizer que o mérito acadêmico mensurado pela publicação de artigos não seja uma medida contaminada por processos que vão além do indivíduo. A produção acadêmica, como qualquer outro processo, é um fenômeno resultante em grande parte do contexto histórico, social e político.

E o que isso tem a ver com concursos para seleção de professores/professoras universitários no Brasil? Se adotarmos a ideia de que o mérito acadêmico deveria ter maior peso nas seleções, e de que a prova escrita é um método obsoleto e idiossincrático, que deveria ser abandonado dos processos de seleção, provavelmente teríamos universidades mais homogêneas em relação ao local de origem de seus professores/professoras. Além disso, provável veríamos aumentar ainda mais a diferença em produção científica entre as universidades no eixo sul sudeste e capitais em relação as universidades do interior do país. Em um momento que tanto discutimos sobre diversidade e inclusão, dar mais peso ao mérito acadêmico, representado predominantemente pela quantidade de artigos publicados, ajudaria atingir a desejada equidade dentro da universidade pública brasileira? Na melhor das hipóteses me parece que reforçaria apenas a manutenção do recorte social e geográfico que vemos na produção científica.

Ao mesmo tempo, ao dizer que atribuir maior peso ao chamado mérito científico não soluciona problemas de representatividade na universidade, não significa afirmar que as outras etapas do processo de seleção, como a prova escrita, são a solução. O ponto que coloco é, o aumento da importância do mérito científico numa seleção pública para professor universitário, este quase uninamamente entendido como quantidade de artigos publicados, não garante a chamada isonomia ou tampouco torna o processo mais justo. Isso leva para meu segundo ponto.

## Brasil e seu sistema único de seleção que inclui provas escritas: maior peso ao mérito acadêmico garante um processo mais isonômico?

O argumento de que o processo de seleção de professores universitários no Brasil é obsoleto, quase sempre vem acompanhado da afirmação de que tal processo é quase exclusivo do Brasil. Concordo com tal argumento, acredito que, se existente, são raros os exemplos de outros países que adotam uma prova escrita como parte de um processo seletivo para contratação de professores universitários. A questão para mim é, independente de concurso público regido por editais federais ou estaduais, a premissa básica de qualquer participante é de que a seleção irá seguir o princípio da [isonomia](https://www.cnmp.mp.br/portal/institucional/476-glossario/8017-isonomia#:~:text=Igualdade%20legal%20para%20todos.,artigo%205%C2%BA%20da%20Constitui%C3%A7%C3%A3o%20Federal). Acredito que nenhuma pessoa estaria de acordo em participar de um processo onde a regra inicial diz que você será julgado de maneira desigual, visto que o organizador tem alguma preferência em relação a certo candidato/candidata. Eu, pelo menos, pouparia meu tempo. Portanto, assumindo que a isônomia de processos seletivos é uma necessidade exigida por lei ou, no mínimo, uma regra moral, podemos dizer que "concursos" que ocorrem em todo o resto do mundo, por não apresentarem uma etapa escrita, ou que dão maior peso a produção científica, se aproximam mais do que julgamos ser isonômico?

[Há evidência sistematizada (através de estudos)](), bem como histórias e experiências pessoais que me fazem acreditar que a resposta para essa pergunta seja não. O ponto aqui não é como se dá um processo seletivo, nem como deveria ser (não tenho a resposta final para isso). Mas sim, o fato de que mesmo um processo onde o mérito científico tem 100% do valor na seleção, não vai garantir maior isônomia.
Mais uma vez, assumindo que isonomia neste contexto representa o frio dos números de artigos, prêmios, financimentos adquiridos e fator de impacto das revistas que o candidato/candidata publicou. Nesse processo que apresenta como único critério o mérito acadêmico, o que terá mais peso? Um prêmio internacional terá mais valor que um artigo? Artigos como primeiro autor terão mais valor que artigos como co-autor? Artigos completos terão mais valor que base de dados ou notas? Trabalhos técnicos (desenvolvimento de software ou programas ou patentes) pesarão quanto? Não é um exercício de retórica, porém acredito que se fizermos essas perguntas para diferentes pesquisadores, vamos ver bastante variação nas respostas.
Portanto, argumentar que uma seleção que tem como baliza principal o mérito científico, este por sua vez representado principalmente pela produção de artigos e conquistas acadêmicas, ainda assim não garante uma seleção mais isonômica, visto que o mérito não é unidimensional, e diferentes processos seletivos atribuirão pesos diferentes ao que chamamos de "mérito".

Mais uma vez, meu argumento não é de que o processo é errado ou certo, mas certamente não podemos argumentar que o processo seletivo brasileiro é mais obsoleto e não isônomico por não premiar adequadamente o que estamos chamando de mérito científico, quando comparado a outros processos de seleção em outros países.

## E agora?

Tentei neste deixar meus centavos de ideias sobre dois pontos: primeiro, o argumento de que o mérito científico expresso através de produção de artigos, apesar de satisfazer o desejo individual de reconhecimento, pode causar, ou no mínimo manter, as estruturas de desigualdades vistas no recorte social da universidade, já que no Brasil este vem acompanhado de fatores sociais e geográficos. Segundo, qualquer processo transparente visa isonomia como princípio de seleção, porém, mesmo em casos onde 100% do peso é dado ao mérito científico, esta não é garantida, visto que o significado de mérito científico pode estar relacionado a diferentes aspectos, algumas vezes abstratos, que não a produção científica por si só.

Ao colocar estes pontos não estou afirmando que a prova escrita é a panacéia para os problemas levantados acima. Mas com certeza não é a razão pela qual temos apenas 10% de doutores/doutoras sendo absorvidos pelas universidades públicas atualmente. Talvez esse assunto não teria tanto holofote nas redes sociais se repensássemos a universidade, a pós-graduação, ou pelo menos se tivéssemos discussões na linha deste texto do [Olavo Amaral](https://www.nexojornal.com.br/colunistas/2023/A-pir%C3%A2mide-financeira-da-carreira-acad%C3%AAmica) (pelo amor de todos os deuses existentes e que já existiram, não confundam com o maluco golpista). 
