---
title: "More than words"
weight: 1
subtitle: "Know the language is not the same as know how to communicate. Communication is a piece of you."
excerpt: "Communication is not just a bunch of words, it is a piece of yourself materialized in the society."
date: 2021-12-29
lastmod: 2021-12-29
draft: false
tags: 
  - second language
  - foreing life
---

## A new driver on the city

About three weeks ago I made one of the hardest decisions of my life, that was move to another country. Two weeks ago
    I landed in the United States to start my new job, a position that I really wanted to get, and an experience that 
    I could not have had the opportunity during the course of my Ph.D. in Brazil due to the cut of budgets promoted by the
    Federal government. So, after 5 interviews I get my new job at Texas A&M University - Corpus Christi, to work developing
    numerical tools for biogeography. I didn't think twice to accept the offer, and in an interval of three months I waived all
    my duties in my home country and bought tickets to US.
    
I was (and already am) very exited to start this new position, but at the same time anxious, nervous, and deeply sad to leave all
    my beloved and start a new life, with a new job, with new people, and a different language. Yes, english is the dominant language of
    science, and in the last four years I wrote more texts in english than in portuguese (my first language), but almost all, if not all, 
    were academic texts, with a limited vocabulary and words that I am very familiar. However, for all the rest of my tasks and 
    activities in Brazil I used to do in my mother tongue, and the life goes much beyond the walls of laboratories and offices in the University.
    Therefore, even used to a different language than my first language, and even with a proficiency test attesting that I have enough written and 
    listening skill to live in a country with english language, deal with the daily activities, all of them requiring to communicate in another
    language than you first language was a shock, a huge amount of energy spend every day, with lots of lost words during conversations. I can 
    assure you, this is the most difficult part for me.


## The Arrival

> *“The grammar of each language is not merely a reproducing instrument for voicing ideas but rather is itself the shaper of ideas.”*

I remember to watch a Hollywood movie a couple years ago, Arrival is the movie`s name. In a nutshell, the movie tells the story of a 
    linguist researcher that try to unveil what a bunch of aliens are trying to do with planet earth after a sudden arrival. To discover 
    the alien's aims the researcher need to learn how to communicate with the aliens. After learn the alien's language the way in which the 
    researcher see the world completely change. Bottom line, the language is much more than a way to express ideas, it influences the way that 
    we perceive the world that surround us.
    
After some years I decided to check if the rationale behind the movie really makes sense, or it was just a good SciFi movie with few scientific 
    basis. After read a couple of articles, I realized that the last option is the real truth behind Arrival. Accordingly to an article in [Smithsonian     Magazine](https://www.smithsonianmag.com/science-nature/does-century-old-linguistic-hypothesis-center-film-arrival-have-any-merit-180961284/), written by Ben Panko, the idea behind the movie, that there is a link between the language and the way people thought has its roots in a hypothesis from the 
    20th century known as "Sapir-Whorf" hypothesis, in other words, the language is not just influenced by the environment and culture of the 
    speakers, but, in its turn, also influence on people's culture and thoughts. Ben Panko highlight that, despite seductive for its simplicity and 
    exoctiness, the Sapir-Whorf hypothesis finds much more support in writers and would-be intellectuals than in respected anthropologists and linguistic researchers like Noam Chomsky and [Steven Pinker](https://en.wikipedia.org/wiki/The_Language_Instinct).

What I know is that I really liked the movie, it catches my attention, as the classic "Alien" movie also did, and, after some internet search, with similar now I now that both shared similarities in the amount of scientific plausibility.
The movie was was a recommendation of my ex-girlfriend, that received the recommendation from another friend of her, a Portuguese Professor (IMHO a person that fits well in the would-be intellectual category). At that time, she said to me that the movie present a strong basis on 
    linguistic theory, accordingly to his would be linguistic friend. After a couple years I watched the movie for the second time, few weeks after my
    arrival in North American, and the movie still catched my attention, specially in a moment in which I am in the need to learn how to 
    interpret and express myself in a language that is not my native language. Currently, I'm feelling that I share a pretty much similarities with
    the Aliens of Arrival movie in the sense that I am trying to express my ideas, however, not the way a really wanted to do.
    
## Me Latin, you American..

Ok, from now, what are you supposed to do with this information
